<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()) : ?>
                <?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>  product bundle option"
                       name="bundle_option[<?= $block->escapeHtml($_option->getId()) ?>]"
                       value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
                <div class="control">
                    <input <?php if (!$_selections[0]->getSelectionCanChangeQty()) { echo 'disabled="disabled"'; }?>
                            id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                            class="input-text qty<?php if (!$_selections[0]->getSelectionCanChangeQty()) { echo 'qty-disabled'; } ?>"
                            type="number"
                            name="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                            data-selector="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                            value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionQty() * 1) ?>"/>
                </div>
            <?php else :?>
                <?php foreach ($_selections as $_selection) : ?>
                    <div class="field choice">
                        <input class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?> checkbox product bundle option change-container-classname"
                               id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                               type="checkbox"
                               name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>][<?= $block->escapeHtmlAttr($_selection->getId()) ?>]"
                               data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>][<?= $block->escapeHtmlAttr($_selection->getId()) ?>]"
                               value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"/>
                        <label class="label"
                               for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>">
                            <span><?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection) ?></span>
                            <br/>
                            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                        </label>
                    </div>
                    <div class="control">
                        <input <?php if (!$_selection->isSaleable() || !$_selection->getSelectionCanChangeQty()) { echo 'disabled = "disabled"'; }?>
                                id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input"
                                class="input-text qty<?php if (!$_selection->getSelectionCanChangeQty()) { echo ' qty-disabled'; } ?>"
                                type="number"
                                name="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                                data-selector="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                                value="<?= $block->escapeHtmlAttr($_selection->getSelectionQty() * 1) ?>"/>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></div>
            <?php endif; ?>
        </div>
    </div>
</div>
