<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
                <?php foreach ($_selections as $_selection) : ?>
                    <div class="field choice">
                        <input class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?> checkbox product bundle option change-container-classname"
                               id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                               type="hidden"
                               name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>][<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>]"
                               data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>][<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>]"
                               value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"/>
                        <label class="label"
                               for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>">
                            <span><?= /* @noEscape */ $block->getSelectionQtyTitlePrice($_selection) ?></span>
                            <br/>
                            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                        </label>
                    </div>
                    <div class="control">
                        <input <?php if (!$_selection->isSaleable() || !$_selection->getSelectionCanChangeQty()) { echo 'disabled = "disabled"'; }?>
                                id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>-qty-input"
                                class="input-text qty<?php if (!$_selection->getSelectionCanChangeQty()) { echo ' qty-disabled'; } ?>"
                                type="number"
                                name="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                                data-selector="bundle_option_qty[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                                value="<?= $block->escapeHtmlAttr($_selection->getSelectionQty() * 1) ?>"/>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-container"></div>
        </div>
    </div>
</div>
